from PrintTags import *

print('\n')
yellow('----------------------------------')
yellow('         Colorized strings')
yellow('----------------------------------')
print('\n')

print(Colors.black('Black'))
print(Colors.red('Red'))
print(Colors.green('Green'))
print(Colors.yellow('Yellow'))
print(Colors.blue('Blue'))
print(Colors.magenta('Magenta'))
print(Colors.cyan('Cyan'))
print(Colors.white('White'))

print('\n')
cyan('----------------------------------')
cyan('           Colored printouts')
cyan('----------------------------------')
print('\n')

black('Black')
red('Red')
green('Green')
yellow('Yellow')
blue('Blue')
magenta('Magenta')
cyan('Cyan')
white('White')

print('\n')
green('----------------------------------')
green('             Tag off')
green('----------------------------------')
print('\n')

info('Info', tag=False)
success('Success', tag=False)
notice('Notice', tag=False)
timeout('Timeout', tag=False)
warn('Warn', tag=False)
error('Error', tag=False)

print('\n')
blue('----------------------------------')
blue('             Tags on')
blue('----------------------------------')
print('\n')

info('Info')
success('Success')
notice('Notice')
timeout('Timeout')
warn('Warn')
error('Error')

print('\n')
