from PrintTags import *

print('\n')
cyan('----------------------------------')
cyan('              Colors')
cyan('----------------------------------')
print('\n')

black('Black')
red('Red')
green('Green')
yellow('Yellow')
blue('Blue')
magenta('Magenta')
cyan('Cyan')
white('White')

print('\n')
green('----------------------------------')
green('             Tag off')
green('----------------------------------')
print('\n')

info('Info', tag=False)
success('Success', tag=False)
notice('Notice', tag=False)
timeout('Timeout', tag=False)
warn('Warn', tag=False)
error('Error', tag=False)

print('\n')
blue('----------------------------------')
blue('             Tags on')
blue('----------------------------------')
print('\n')

info('Info')
success('Success')
notice('Notice')
timeout('Timeout')
warn('Warn')
error('Error')
print('\n')